49 set row length to standard browser window
hpi-swa-teaching/poppy-print pull request #76
Opened 2022-06-16 15:36 UTC by janiswehen

2022-06-16 15:52 UTC, Yannis-Hofmann requested changes

2022-06-16 15:52 UTC, Yannis-Hofmann commented on packages/PoppyPrint-Core.package/PPFormatterConfig.class/instance/maxLineWidth..st
> +maxLineWidth: anObject
anInteger vs anObject

2022-06-16 15:52 UTC, Yannis-Hofmann commented on packages/PoppyPrint-Core.package/PPFormatterConfig.class/instance/formatToMaxLineWidth..st
> +formatToMaxLineWidth: anObject
aBoolean vs anObject

2022-06-16 15:52 UTC, Yannis-Hofmann commented on packages/PoppyPrint-Tests.package/PPWondowFormatterTest.class/properties.json
> +	"name" : "PPWondowFormatterTest",
This should be PPWindowFormatterTest

2022-06-18 09:06 UTC, kdauer requested changes

2022-06-18 09:06 UTC, kdauer commented on packages/PoppyPrint-Tests.package/PPFormatterTest.class/instance/testStandaredWindowWidth1.st
> +testStandaredWindowWidth1
Should be Standard or could be called Default, maybe Default is a better naming convention

2022-06-18 09:06 UTC, kdauer commented on packages/PoppyPrint-Tests.package/PPFormatterTest.class/instance/testStandaredWindowWidth2.st
> +testStandaredWindowWidth2
Also Standard of Default

2022-06-18 09:06 UTC, kdauer commented on packages/PoppyPrint-Tests.package/PPFormatterTest.class/instance/testStandaredWindowWidth3.st
> +testStandaredWindowWidth3
Standard or Default

2022-06-23 09:18 UTC, kdauer requested changes

2022-06-23 09:18 UTC, kdauer commented on packages/PoppyPrint-Core.package/PPWindowFormatter.class/instance/putIndentedNewlineAndWord.st
> +	index := index + wordWidth + 1.
Is this a trailing dot?

2022-06-23 09:18 UTC, kdauer commented on packages/PoppyPrint-Core.package/PPWindowFormatter.class/instance/putSeperatorAndWord.st
> +	index := index + wordWidth + 1
Or is the dot here missing?

2022-06-23 09:18 UTC, kdauer commented on packages/PoppyPrint-Tests.package/PPWindowFormatterTest.class/instance/testFormatingToDefaultWindowWidth3.st
> +testFormatingToDefaultWindowWidth3
testFormattingToDefaultWindowWidth3, Formatting

2022-06-23 09:18 UTC, kdauer commented on packages/PoppyPrint-Tests.package/PPWindowFormatterTest.class/instance/testFormatingToDefaultWindowWidth1.st
> +testFormatingToDefaultWindowWidth1
Formatting

2022-06-23 09:18 UTC, kdauer commented on packages/PoppyPrint-Tests.package/PPWindowFormatterTest.class/instance/testFormatingToDefaultWindowWidth2.st
> +testFormatingToDefaultWindowWidth2
Formatting

2022-06-23 09:18 UTC, kdauer commented on packages/PoppyPrint-Tests.package/PPWindowFormatterTest.class/instance/testFormatingToZeroWidth1.st
> +testFormatingToZeroWidth1
Formatting

2022-06-23 15:06 UTC, kdauer approved these changes

2022-06-23 15:08 UTC, merged